package models

import (
	"time"

	"gorm.io/gorm"
)

// DeviceSession is the GORM model for auth.device_sessions. One row
// per active login; revoking a session immediately blocks access even
// if the caller still holds a valid access token.
type DeviceSession struct {
	ID               int64  `gorm:"primaryKey;autoIncrement" json:"id"                msgpack:"id"`
	UserID           int64  `                                json:"user_id"            msgpack:"user_id"`
	Platform         string `                                json:"platform"           msgpack:"platform"`
	Manufacturer     string `                                json:"manufacturer"       msgpack:"manufacturer"`
	Model            string `                                json:"model"              msgpack:"model"`
	Version          string `                                json:"version"            msgpack:"version"`
	SDK              string `                                json:"sdk"                msgpack:"sdk"`
	Brand            string `                                json:"brand"              msgpack:"brand"`
	Hardware         string `                                json:"hardware"           msgpack:"hardware"`
	Board            string `                                json:"board"              msgpack:"board"`
	Device           string `                                json:"device"             msgpack:"device"`
	Product          string `                                json:"product"            msgpack:"product"`
	IsPhysicalDevice bool   `                                json:"is_physical_device" msgpack:"is_physical_device"`
	Name             string `                                json:"name"               msgpack:"name"`
	// Identifier is the app-level session identifier, generated by
	// the client at first login and reused across token rotations
	// for the same device.
	Identifier string `                                json:"identifier"         msgpack:"identifier"`
	// DeviceID is the hardware identifier supplied by the client
	// (e.g. Android device ID). Validated on every request via the
	// X-Device-Id header; a mismatch returns 401 DEVICE_MISMATCH.
	DeviceID string `                                json:"device_id"          msgpack:"device_id"`

	LastActivity time.Time `json:"last_activity" msgpack:"last_activity"`
	IPAddress    string    `json:"ip_address"    msgpack:"ip_address"`
	UserAgent    string    `json:"user_agent"    msgpack:"user_agent"`
	Location     string    `json:"location"      msgpack:"location"`

	// RevokedAt is the timestamp when this session was explicitly
	// revoked (logout, password change, admin action). A non-nil
	// value means the session is no longer valid regardless of token
	// expiry.
	RevokedAt     *time.Time `json:"revoked_at,omitempty"     msgpack:"revoked_at,omitempty"`
	RevokedReason string     `json:"revoked_reason,omitempty" msgpack:"revoked_reason,omitempty"`

	CreatedAt time.Time `json:"created_at" msgpack:"created_at"`

	User User `gorm:"foreignKey:UserID" json:"user" msgpack:"user"`
}

// BeforeCreate defaults LastActivity to the current time when the
// caller did not set it explicitly.
func (ds *DeviceSession) BeforeCreate(tx *gorm.DB) error {
	if ds.LastActivity.IsZero() {
		ds.LastActivity = time.Now()
	}
	return nil
}

// TableName returns the schema-qualified table name for GORM.
func (DeviceSession) TableName() string {
	return "auth.device_sessions"
}

// IsValid reports whether the session is neither revoked nor idle
// longer than timeout.
func (ds *DeviceSession) IsValid(timeout time.Duration) bool {
	return !ds.IsRevoked() && !ds.IsInactive(timeout)
}

// IsRevoked reports whether the session was explicitly revoked.
func (ds *DeviceSession) IsRevoked() bool {
	return ds.RevokedAt != nil && !ds.RevokedAt.IsZero()
}

// IsInactive reports whether the session has not been active within
// the given timeout window.
func (ds *DeviceSession) IsInactive(timeout time.Duration) bool {
	return time.Since(ds.LastActivity) > timeout
}

// GetDeviceInfo returns a map of device hardware and OS metadata
// suitable for logging and the session-list API response.
func (ds *DeviceSession) GetDeviceInfo() map[string]any {
	return map[string]any{
		"platform":           ds.Platform,
		"manufacturer":       ds.Manufacturer,
		"model":              ds.Model,
		"version":            ds.Version,
		"sdk":                ds.SDK,
		"brand":              ds.Brand,
		"hardware":           ds.Hardware,
		"board":              ds.Board,
		"device":             ds.Device,
		"product":            ds.Product,
		"is_physical_device": ds.IsPhysicalDevice,
		"name":               ds.Name,
		"identifier":         ds.Identifier,
		"device_id":          ds.DeviceID,
	}
}
