dev:
  project_id: ${FIREBASE_PROJECT_ID:-}
  credentials_file: ${FIREBASE_CREDENTIALS_FILE:-secrets/firebase-dev.json}

prod:
  project_id: ${FIREBASE_PROJECT_ID:-}
  credentials_file: ${FIREBASE_CREDENTIALS_FILE:-secrets/firebase-prod.json}
